AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Resources health overview API,
  
  Allows Grafana to query AWS resource statuses to create a Health dashboard.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 12

Resources:
  QueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: query/
      Handler: handler.lambda_handler
      Runtime: python3.8
      Events:
        Query:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /query
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HealthApi:
    Description: "API Gateway endpoint URL for Prod stage for health api"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health/"
  QueryFunction:
    Description: "Query statuses Lambda Function ARN"
    Value: !GetAtt QueryFunction.Arn
  QueryFunctionIamRole:
    Description: "Implicit IAM Role created for Query Function"
    Value: !GetAtt QueryFunctionRole.Arn
